# Generated by Django 5.0.6 on 2024-09-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(default='Descripción por defecto', max_length=255)),
            ],
        ),
    ]
