# Generated by Django 5.1.1 on 2024-10-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0002_carrito_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
