# Generated by Django 5.1.1 on 2024-10-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0003_listadeseados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listadeseados',
            unique_together={('usuario', 'producto')},
        ),
    ]
