# Generated by Django 5.0.6 on 2024-12-11 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0003_especificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.almacenamiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.producto')),
            ],
            options={
                'unique_together': {('producto', 'almacenamiento')},
            },
        ),
        migrations.CreateModel(
            name='ProductoColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.producto')),
            ],
            options={
                'unique_together': {('producto', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.modelo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.producto')),
            ],
            options={
                'unique_together': {('producto', 'modelo')},
            },
        ),
        migrations.DeleteModel(
            name='Especificacion',
        ),
    ]
