# Generated by Django 5.0.6 on 2024-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0003_alter_usuario_email_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
