# Generated by Django 5.1.2 on 2024-11-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0003_carrito_comprado_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
