# Generated by Django 5.0.6 on 2024-12-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0004_almacenamiento_color_modelo_productoalmacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_tg',
            field=models.CharField(default='tarjeta amd alta gama', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='memoria_ram',
            field=models.CharField(default='2 ram', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='procesador',
            field=models.CharField(default='Sin descripción', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='sistema_operativo',
            field=models.CharField(default='Windows', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño_pantalla',
            field=models.CharField(default='1470 x 2010', max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='tarjeta_grafica',
            field=models.CharField(default='Si', max_length=50),
        ),
    ]
