# Generated by Django 5.1.3 on 2024-12-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0005_almacenamiento_color_modelo_productoalmacenamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenamiento',
            name='capacidad',
            field=models.IntegerField(unique=True),
        ),
    ]
